### ISSUE TITLE
False positives for repeated imports (removal of F401)

### ISSUE THREAD

**Issue by PeterJCLaw** [asottile/yesqa#102]
Given:
``` python
from .foo import thing  # noqa: F401
from .bar import thing  # noqa: F401, F811
from .baz import thing  # noqa: F401, F811
```
which may happen when importing for the purposes of registering values rather than for the purposes of actually importing the symbols, `yesqa` will incorrectly remove the first two `F401` markers presumably because the symbol appears later in the file:
``` python
from .foo import thing
from .bar import thing  # noqa: F811
from .baz import thing  # noqa: F401, F811
```

**Comment by asottile** [comment]
this is working correctly:

```console
$ pip freeze
flake8==4.0.1
mccabe==0.6.1
pycodestyle==2.8.0
pyflakes==2.4.0
tokenize-rt==4.2.1
yesqa==1.3.0
$ cat t.py 
from .foo import thing  # noqa: F401
from .bar import thing  # noqa: F401, F811
from .baz import thing  # noqa: F401, F811
$ flake8 t.py
$ yesqa t.py
Rewriting t.py
$ flake8 t.py
$ cat t.py 
from .foo import thing
from .bar import thing  # noqa: F811
from .baz import thing  # noqa: F401, F811
```

**Comment by PeterJCLaw** [comment]
Ahh, worked it out. For some reason the `F401`s were making `isort` skip those lines too. Removing the `F401`s was giving me various errors from `flake8-isort` which I failed to realise were different.

**Comment by asottile** [comment]
sounds like isort has an incompatible interpretation of `noqa` -- probably worth raising there
