### ISSUE TITLE
Yesqa compatibility with bandit

### ISSUE THREAD

**Issue by lsorber** [asottile/yesqa#136]
Hi, an issue I've come across is that yesqa will remove false positive `# noqa` statements that are actually necessary for bandit.

Is there a way to configure yesqa to ignore bandit noqas, or to otherwise take into account that another linter will run besides flake8?

I'm aware of the flake8-bandit plugin, but it hasn't been very dependable in my experience (e.g. it broke when flake8 v5.0 was released).

**Comment by asottile** [comment]
bandit should not use `noqa` as that's flake8's marker
