### ISSUE TITLE
Rules with more than 3 letters are not recognised

### ISSUE THREAD

**Issue by PLPeeters** [asottile/yesqa#208]
This causes rules with more than 3 letters not to be recognised:

https://github.com/asottile/yesqa/blob/904a50eb292c09dcdfef07c2b7132623a0edbc51/yesqa.py#L19

It wanted to use this, but since I'm using flake8-async it's not working as it should since its rules are labeled `ASYNCXXX`. I'm wondering if it even makes sense to limit label length since it has to be prefixed with `noqa:` anyway?

Tangentially, the rule expression could be made more "typo"-friendly by replacing the ` ?` portion by ` *` (and arguably `\s*` for readability):

https://github.com/asottile/yesqa/blob/904a50eb292c09dcdfef07c2b7132623a0edbc51/yesqa.py#L21

Otherwise if we accidentally double-space after noqa it's not going to match, unless I'm misunderstanding.

**Comment by PLPeeters** [comment]
Is that documented anywhere? I can't seem to find such a restriction in the flake8 documentation and I'd like to raise a documented issue on the [flake8-async](https://github.com/python-trio/flake8-async) repo if such a restriction indeed exists.

**Comment by asottile** [comment]
yes. the docs https://flake8.pycqa.org/en/latest/plugin-development/registering-plugins.html#registering-a-plugin-with-flake8

**Comment by PLPeeters** [comment]
Okay, so after some back and forth and more reading, as I understand it this ended up being enforced because longer codes would cause Flake8 to silently misbehave. That indeed sounds like a necessary fix, but what puzzles me is why it did not lead to fixing the misbehaviour down the line to avoid breaking existing plugins? I'd be keen to get your insights into this if you have the time.

**Comment by asottile** [comment]
I don't have the time.  read the issues yourself
