### ISSUE TITLE
Skip # noqa check on typing

### ISSUE THREAD

**Issue by youngyjd** [asottile/yesqa#26]
I have a usecase that pep8 `max-line-length` is set to `79` and at the same time I have a type annotation that exceeds `79` characters. 

For example:
```
        # type: () -> Optional[List[Tuple[str, str, None, None, None, None, None]]]
```

I tried to search for multiline annotation but got nothing. I wonder whether we can remove end line noqa check on python typing comment?

**Comment by asottile** [comment]
I think you're misunderstanding what this tool does?

This tool auto-remove `# noqa` comments which are unnecessary -- it isn't the tool responsible for marking lines as "too long"

I think what you want to do is:

```python
# type: ... # noqa: E501
```

**Comment by youngyjd** [comment]
@asottile yeah. I understand. I mean, I indeed tried
```
# type: ... # noqa: E501
```
and then `yesqa` removes `# noqa: E501` as it feels this `# noqa` is unnecessary as it is in comment?

**Comment by asottile** [comment]
do you have a concrete code example I can try out?

**Comment by asottile** [comment]
I did find two cases which seemed related, not sure if they were the same but this wasn't getting fixed:

```python
# a   # noqa
```

so I adjusted the comment removal routine

**Comment by youngyjd** [comment]
@asottile thank you!!! Tested the new version and it works.
It makes sense that 
```
# a   # noqa
```
does not need to be handled as it is easy to split a long comment into several lines.

**Comment by asottile** [comment]
Yeah as far as I could tell it was removing the whole comment to validate if it was fine instead of just the noqa part. This was making it think the content wasn't necessary and removing it
