### ISSUE TITLE
Could we also address `# type: ignore`?

### ISSUE THREAD

**Issue by pykong** [asottile/yesqa#29]
Thanks for putting up this tiny gem of a code quality enhancer.

I wonder how you would think about extending `yesqa` to also tackle redundant ignore statement of MyPy? Likely the current logic might be readily extended to do so.

Not a duplicate, but related: #26

**Comment by asottile** [comment]
probably! or another project which uses the same internal -- at least with mypy `--warn-unused-ignores` can expose this (but it doesn't auto-rewrite for you)

**Comment by pykong** [comment]
Thank you.
I do not think this is super important.
I am closing this. Feel free to re-open if deemed required.
