### ISSUE TITLE
Can convert limited noqa's to generic noqa's

### ISSUE THREAD

**Issue by plinss** [asottile/yesqa#40]
If you have a line of code that has a flake8 error, but different from the one listed in a noqa comment, the tool will convert `# noqa: X000` to `# noqa:` which then masks the other error.

Example:
```
if x==2:  # noqa: E101
    pass
```
becomes:
```
if x==2:  # noqa: 
    pass
```
which now suppresses E225

**Comment by asottile** [comment]
hello!  thanks for the issue -- I've fixed this in #40 and it has been released as part of v1.1.1
