### ISSUE TITLE
BUG False positive removal on windows due to IOError

### ISSUE THREAD

**Issue by s-weigand** [asottile/yesqa#45]
First of all thanks for yet another great tool 😄 
Today I was adding `pre-commit` (one hook at a time) to an existing codebase and when I added `yesqa`, it started having a nasty fight with the `flaek8` hook. When I ran `pre-commit run --all` on linux (WSL) there was no problem, so I did some digging.

When I started printing the responses from `flake8`, I found that all false positive removals returned `0       E902`, which [corresponds to an IOError](https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes).

I added:

```python
        print(filename)
        print(line)
```
to:
https://github.com/asottile/yesqa/blob/7a009f3ee493c796827ee334f9058b110a0e0db8/yesqa.py#L25-L30

My guess is that this is due to [`NamedTemporaryFile` only being partially supported by windows](https://docs.python.org/3.8/library/tempfile.html#tempfile.NamedTemporaryFile).
https://github.com/asottile/yesqa/blob/7a009f3ee493c796827ee334f9058b110a0e0db8/yesqa.py#L121-L128

My local quick and dirty hotfix for now is adding another check, like the one you use:
https://github.com/asottile/yesqa/blob/7a009f3ee493c796827ee334f9058b110a0e0db8/yesqa.py#L130-L132

```python
    if any('E902' in v for v in flake8_results.values()):
        print(f'{filename}: IO error (skipping)')
        return 0
```

P.S.: Not sure where `E999` comes from, but  judging by the error message this might be a typo/the error code changed and you might have meant to write [`E901`](https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes)

**Comment by asottile** [comment]
IOError should never occur, there should be a fix to avoid that not skip it -- my guess is you can reproduce the problem with the testsuite on windows

**Comment by asottile** [comment]
also your link is about pycodestyle which is unrelated to flake8:

```
$ flake8 t.py
t.py:1:12: E999 SyntaxError: invalid syntax
```

**Comment by s-weigand** [comment]
Just tested it with the file `pre-commit` cached in its env, let me do a quick fork and run the `yesqa` testsuite.

> also your link is about pycodestyle which is unrelated to flake8:

Ops totaly overlooked it in the [flake8 docs](https://flake8.pycqa.org/en/latest/user/error-codes.html), since noobie me only looked at the table 😞

**Comment by asottile** [comment]
fwiw your hack just turns off yesqa since every call will result in E902

**Comment by s-weigand** [comment]
> fwiw your hack just turns off yesqa since every call will result in E902

Uff that's no good.

Just ran the testsuite locally and it fails as well `16 failed, 11 passed`.

**Comment by asottile** [comment]
the trick is probably to close the temporary file before calling, or use TemporaryDirectory instead

**Comment by s-weigand** [comment]
> the trick is probably to close the temporary file before calling, or use TemporaryDirectory instead

Yeah that sounds like a plan, since windows is very ... particular with file access (i.e. locked files until restart or you use an extra tool on them).
But the 'destroy on close' mechanism of `NamedTemporaryFile` is very elegant. 
Maybe implement the temp file different for windows only?

**Comment by asottile** [comment]
not really that convenient when you have to maintain twice as much code :P just one way to do it please

**Comment by s-weigand** [comment]
> not really that convenient when you have to maintain twice as much code :P just one way to do it please

Ok point taken.

This fixes the tests on windows, and Linux still works.

```python
    with tempfile.NamedTemporaryFile(
        dir=os.path.dirname(filename),
        prefix=os.path.basename(filename),
        suffix='.py',
        delete=False
    ) as tmpfile:
        tmpfile.write(src_no_comments.encode())
        tmpfile.flush()
        flake8_results = _run_flake8(tmpfile.name)
    os.remove(tmpfile.name)
```

Do you want me to make a PR?

**Comment by asottile** [comment]
that isn't quite correct, if `_run_flake8` (or anything else in the `with` block) were to raise, it would leak the temporary file

It's probably best to use TemporaryDirectory and write a file inside that.

**Comment by s-weigand** [comment]
> that isn't quite correct, if `_run_flake8` (or anything else in the `with` block) were to raise, it would leak the temporary file
> 
> It's probably best to use TemporaryDirectory and write a file inside that.

Yeah I was thinking about that too.
Guess the best approach to ensure that the temp files get deleted, would be to create the `TemporaryDirectory` in `main` before the for loop, pass it to `fix_file`, wrap the for loop in a `try except` and delete the `TemporaryDirectory` with a `finally`.
Or is there a better way to implement a `finally`-like insurance that code runs no matter what?
Also I guess this is a rare case where you would want catch a `BaseException`, so files also get deleted after a "KeyboardInterrupt" (and yes I watch your videos 🤣 )
One last question than Twitch can have you back 😋 .
Would you rather prefer the temp folder to be in the system temp or have it in the repo (i.e. `yesqa-temp`), so users can spot it quicker if something goes wrong.

**Comment by asottile** [comment]
I wouldn't worry about sharing the tempdir, it's going to be fast enough to just create and delete it each time

basically just

```python
with tempfile.TemporaryDirectory() as tmpdir:
    with open(os.path.join(tmpdir, 't.py'), 'w') as f:
       ...
   ...
```

**Comment by s-weigand** [comment]
BTW, also huge props, I think those are the quickest replies I ever got on any issue.

**Comment by asottile** [comment]
also you'd use `try: finally:` no need to catch an exception if you were going to approach it that way!

**Comment by s-weigand** [comment]
Sooo I played a bit around, and it looks like that `TemporaryDirectory` has a similar issue as `NamedTemporaryFile`, I guess this is an issue with how windows handles the whole `set`->`acquire`->`release` mechanisms with file locking.
What do you think of the following approach?
```python
    try:
        with tempfile.NamedTemporaryFile(
            dir=os.path.dirname(filename),
            prefix=os.path.basename(filename),
            suffix='.py',
            delete=False
        ) as tmpfile:
            tmpfile.write(src_no_comments.encode())
            tmpfile.flush()
            flake8_results = _run_flake8(tmpfile.name)
    finally:
        if os.path.exists(tmpfile.name):
            os.remove(tmpfile.name)
```
This change [should prevent the leak of temporary files](https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions).

P.S.: Didn't watch all the `anthony explains` videos YET (maybe it exists already), but a `try: except: else: finally:` and the combinations (similar to `all python argument / parameter types`) would be awesome 😄

**Comment by asottile** [comment]
it works fine???

```
(venv) C:\Users\Anthony\workspace\babi>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
>>> import os.path
>>> import subprocess
>>> with tempfile.TemporaryDirectory() as tmpdir:
...     fname = os.path.join(tmpdir, 'f.py')
...     with open(fname, 'w') as f:
...         f.write('import os')
...     import sys
...     subprocess.call((sys.executable, '-mflake8', fname))
...
9
C:\Users\Anthony\AppData\Local\Temp\tmpkn1986mo\f.py:1:1: F401 'os' imported but unused
C:\Users\Anthony\AppData\Local\Temp\tmpkn1986mo\f.py:1:10: W292 no newline at end of file
1
```

**Comment by s-weigand** [comment]
I found my error, I was constructing my `tmpfile_path`, with `filename` instead of `os.path.basename(filename)` :dizzy_face:
Some sleep and coffee helped a lot to find that error 😂 
Now getting the `flake8_results` looks like this:
```python
    with tempfile.TemporaryDirectory() as tmpdir:
        tmpfile_path = os.path.join(tmpdir, os.path.basename(filename))
        with open(tmpfile_path, "wb") as tmpfile:
            tmpfile.write(src_no_comments.encode())
        flake8_results = _run_flake8(tmpfile_path)
```

**Comment by asottile** [comment]
sounds good, send a patch!

you'll probably also want to set up CI for windows, you can probably do something similar to what is done for pyupgrade: https://github.com/asottile/pyupgrade/blob/f766c29ec4bb6cf2674b81959871e59d5400380a/azure-pipelines.yml#L17-L20
