### ISSUE TITLE
How to run on a native namespace package

### ISSUE THREAD

**Issue by jamesbraza** [asottile/yesqa#47]
From reading through the unit tests/source, it seems like this is designed to be run on individual files only (I may be wrong).

I would like to run `yesqa` on an entire native namespace package.    How can this be done?

---

**Current Solution**

A solution is to pipe the output of something like `find` to `yesqa`:

```bash
find . -type f -name "*.py" | xargs yesqa
```

([inspiration](https://github.com/PyCQA/pylint/issues/352#issuecomment-474804816))

---

**Versions**

```
Python==3.7.9
flake8==3.8.4
yesqa==1.2.2
```

**Comment by asottile** [comment]
your current solution works fine
