### ISSUE TITLE
Grab `additional_dependencies` from `.pre-commit-config.yaml`

### ISSUE THREAD

**Issue by Cielquan** [asottile/yesqa#49]
Would it be possible to add a flag for `yesqa` so that it takes the pre-commit config searches for a flake8 hook and grabs its `additional_dependencies` and sets them for itself? And maybe also the specified flake8-version?
This would take the need to specify them twice, if you use flake8 with pre-commit also.

As you can set the same hook multiple times, by default it should take the first it finds, but can be configured to take the second or so.

@asottile What do you think about this idea?

**Comment by asottile** [comment]
no, that's not how pre-commit works

**Comment by Cielquan** [comment]
Ok, sad to hear, but thanks for the fast answer.

**Comment by Cielquan** [comment]
> @Cielquan There is a clever workaround here if you don't want to repeat the additional_depenencies. Confirmed that this works properly with pre-commit caching.
> 
> ```yaml
> -   repo: https://github.com/pycqa/flake8
>     rev: 3.9.2
>     hooks:
>     -   id: flake8
>         additional_dependencies: &flake8_dependencies
>         - flake8-bugbear==21.9.2
>         - flake8-builtins==1.5.3
>         - flake8-comprehensions==3.6.1
>         - flake8-return==1.1.3
>         - flake8-simplify==0.14.2
> 
> -   repo: https://github.com/asottile/yesqa
>     rev: v1.2.3
>     hooks:
>     -   id: yesqa
>         additional_dependencies: *flake8_dependencies
> ```

Thanks for sharing :)
