### ISSUE TITLE
Incorrectly removes S404 and S603

### ISSUE THREAD

**Issue by wwuck** [asottile/yesqa#56]
I'm using `flake8-bandit` to check a file that uses the `subprocess` module.

```python3
import subprocess  # noqa: S404

subprocess.check_call(['/bin/ls'])  # noqa: S603
```

flake8 reports [S404](https://bandit.readthedocs.io/en/latest/blacklists/blacklist_imports.html#b404-import-subprocess) and [S603](https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html) so I add a `noqa` to each line.

Running `yesqa` on this file incorrectly removes the noqa codes.

**Comment by asottile** [comment]
cannot reproduce:

```console
$ virtualenv venv
created virtual environment CPython3.8.5.final.0-64 in 179ms
  creator CPython3Posix(dest=/tmp/y/q/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/asottile/.local/share/virtualenv)
    added seed packages: pip==20.2.4, setuptools==51.0.0, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
$ . venv/bin/activate
(venv) $ pip install flake8-bandit yesqa
...
(venv) $ babi t.py
(venv) $ yesqa t.py 
(venv) $ cat t.py 
import subprocess  # noqa: S404

subprocess.check_call(['/bin/ls'])  # noqa: S603
```

if you're using `yesqa` through `pre-commit` make sure to list your necessary plugins as part of `additional_dependencies` such as:

```yaml
# ...
    -   id: yesqa
        additional_dependencies: [flake8-bandit]
```

this is covered in the [README](https://github.com/asottile/yesqa#as-a-pre-commit-hook) (it's pretty short)

**Comment by wwuck** [comment]
Ahh thanks for that, don't know why I missed it.
