### ISSUE TITLE
Check only mode

### ISSUE THREAD

**Issue by iakum** [asottile/yesqa#61]
Hi,
thanks for creating this.

I just wonder if it would be possible to make it similar to the pylint's "useless-supression". Meaning, that yesqa runs as a flake8 plugin and just reports (but no changes) not needed "noqa"'s. So a kind of check mode.
Personally, I prefer to see a warning or error instead of letting a program change my code :-D

Best regards,
Kai

**Comment by asottile** [comment]
no thanks
