### ISSUE TITLE
yesqa turns `# noqa: F821,E501` into `# noqa: F821`, but then flake8 reports it

### ISSUE THREAD

**Issue by MarcoGorelli** [asottile/yesqa#67]
Here's an example:
```console
$ cat t.py 
def foo(w: Sequence[int], x: Sequence[int], y: int, z: int) -> bar: ...  # noqa: F821,E501
$ yesqa t.py 
Rewriting t.py
$ cat t.py 
def foo(w: Sequence[int], x: Sequence[int], y: int, z: int) -> bar: ...  # noqa: F821
$ flake8 t.py 
t.py:1:80: E501 line too long (85 > 79 characters)
```

**Comment by asottile** [comment]
heh, quite the edge case -- I guess the noqa-replacer can be fixed to insert dummy characters for those comments -- would you like to take a stab at a fix?

**Comment by MarcoGorelli** [comment]
sure, I'll give it a go!

**Comment by MarcoGorelli** [comment]
> sure, I'll give it a go!

not gonna have a chance to do this until next weekend (24th April), if anyone wants to do it before then they're welcome to take this
