### ISSUE TITLE
support for writing other "noqa" cases

### ISSUE THREAD

**Issue by MRigal** [asottile/yesqa#87]
Hi @asottile 

Thanks for the great package. I was wondering if you could imagine that we could add a configurable `noqa` case, as it always writes it back lower case.

It's actually a blocker for us, as it triggers diffs just because of the case and is also going against our company dev guidelines. We could keep lower case the standard but also make it configurable to accept "NOQA" or "NoQA". I could propose a PR if you accept the idea.

**Comment by asottile** [comment]
declining this feature request: the canonical spelling of noqa is all lower case

I am the flake8 maintainer
