### ISSUE TITLE
Support for "No-yesqa" marker or possibility to skip repairing some flake8 codes

### ISSUE THREAD

**Issue by MRigal** [asottile/yesqa#88]
I use flake8-comprehensions and I have one case where I actually don't want dict comprehension as I run into unhashable errors which I don't have if I construct the dict via iteration over a tuple. Therefore I have a `# NoQA: C404` which I don't want to fix.

What could be possible here? A `# NoQA: C404, no-yesqa` appendix? The possibility to tell to `yesqa` to not fix some flake8 error codes?

**Comment by asottile** [comment]
yesqa never "fixes" anything -- if it's removing the noqa comment then you're missing plugins when running yesqa -- see [the README](https://github.com/asottile/yesqa#as-a-pre-commit-hook)

**Comment by MRigal** [comment]
I found a way around it, but you didn't get my point. I know that it uses flake8 and that it needs the plugins as additional dependencies.

However, they might be some annotations where you don't want `yesqa` to try to QA it (especially with plugins, as some warnings/suggestions might not be as good as in flake8 core). A marker and/or the exclusion of some codes might be useful here...

**Comment by asottile** [comment]
> However, they might

there won't -- yesqa will only remove things where there aren't errors and the exclusions are unnecessary
